version: 0.2

env:
  variables:
    # You can set these in the CodeBuild project env instead of hardcoding:
    # SITE_BUCKET: stock-analytics-site-aminwoolim
    # DISTRIBUTION_ID: REPLACE_WITH_YOUR_CF_DISTRIBUTION_ID
    # API_BASE: https://<api-id>.execute-api.us-east-1.amazonaws.com

phases:
  install:
    commands:
      - echo "AWS CLI: $(aws --version)"

  pre_build:
    commands:
      - echo "Bucket: $SITE_BUCKET  Dist: $DISTRIBUTION_ID"
      # Optionally generate config.json so you don't edit HTML for API URL
      - |
        if [ -n "$API_BASE" ]; then
          echo "{\"BASE\":\"$API_BASE\"}" > config.json
          echo "Wrote config.json with BASE=$API_BASE"
        fi

  build:
    commands:
      - echo "Deploying static assets to s3://$SITE_BUCKET"
      # 1) Upload everything except index.html with long cache
      - aws s3 sync . "s3://$SITE_BUCKET" --delete \
          --exclude ".git/*" --exclude ".github/*" \
          --exclude "buildspec.yml" --exclude "README.md" \
          --exclude "index.html" \
          --cache-control "public, max-age=31536000, immutable"

      # 2) Upload index.html with no-cache so updates show immediately
      - aws s3 cp index.html "s3://$SITE_BUCKET/index.html" \
          --cache-control "no-cache, max-age=0" \
          --content-type "text/html"

      # 3) If config.json exists, upload as no-cache too (env changes apply instantly)
      - |
        if [ -f config.json ]; then
          aws s3 cp config.json "s3://$SITE_BUCKET/config.json" \
            --cache-control "no-cache, max-age=0" \
            --content-type "application/json"
        fi

  post_build:
    commands:
      - echo "Invalidating CloudFront"
      - aws cloudfront create-invalidation \
          --distribution-id "$DISTRIBUTION_ID" \
          --paths "/index.html" "/"

artifacts:
  files:
    - '**/*'
  discard-paths: yes